//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFishPartner.PartnerReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThongTin", Namespace="http://schemas.datacontract.org/2004/07/WebServiceWIki.Models.ViewContractModel")]
    [System.SerializableAttribute()]
    public partial class ThongTin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChuDeTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayTaoTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoidungTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TTMoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenTTKhongDauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenTTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AnTT {
            get {
                return this.AnTTField;
            }
            set {
                if ((this.AnTTField.Equals(value) != true)) {
                    this.AnTTField = value;
                    this.RaisePropertyChanged("AnTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChuDeTT {
            get {
                return this.ChuDeTTField;
            }
            set {
                if ((object.ReferenceEquals(this.ChuDeTTField, value) != true)) {
                    this.ChuDeTTField = value;
                    this.RaisePropertyChanged("ChuDeTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDM {
            get {
                return this.MaDMField;
            }
            set {
                if ((this.MaDMField.Equals(value) != true)) {
                    this.MaDMField = value;
                    this.RaisePropertyChanged("MaDM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNguoiDung {
            get {
                return this.MaNguoiDungField;
            }
            set {
                if ((this.MaNguoiDungField.Equals(value) != true)) {
                    this.MaNguoiDungField = value;
                    this.RaisePropertyChanged("MaNguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaTT {
            get {
                return this.MaTTField;
            }
            set {
                if ((this.MaTTField.Equals(value) != true)) {
                    this.MaTTField = value;
                    this.RaisePropertyChanged("MaTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayTaoTT {
            get {
                return this.NgayTaoTTField;
            }
            set {
                if ((this.NgayTaoTTField.Equals(value) != true)) {
                    this.NgayTaoTTField = value;
                    this.RaisePropertyChanged("NgayTaoTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoidungTT {
            get {
                return this.NoidungTTField;
            }
            set {
                if ((object.ReferenceEquals(this.NoidungTTField, value) != true)) {
                    this.NoidungTTField = value;
                    this.RaisePropertyChanged("NoidungTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TTMoi {
            get {
                return this.TTMoiField;
            }
            set {
                if ((this.TTMoiField.Equals(value) != true)) {
                    this.TTMoiField = value;
                    this.RaisePropertyChanged("TTMoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenTTKhongDau {
            get {
                return this.TenTTKhongDauField;
            }
            set {
                if ((object.ReferenceEquals(this.TenTTKhongDauField, value) != true)) {
                    this.TenTTKhongDauField = value;
                    this.RaisePropertyChanged("TenTTKhongDau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenTT {
            get {
                return this.TokenTTField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenTTField, value) != true)) {
                    this.TokenTTField = value;
                    this.RaisePropertyChanged("TokenTT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="PartnerService", ConfigurationName="PartnerReference.WebPartner")]
    public interface WebPartner {
        
        [System.ServiceModel.OperationContractAttribute(Action="PartnerService/WebPartner/LayTT", ReplyAction="PartnerService/WebPartner/LayTTResponse")]
        WebFishPartner.PartnerReference.ThongTin LayTT(string tokenService, string tokenInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="PartnerService/WebPartner/LayTT", ReplyAction="PartnerService/WebPartner/LayTTResponse")]
        System.Threading.Tasks.Task<WebFishPartner.PartnerReference.ThongTin> LayTTAsync(string tokenService, string tokenInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebPartnerChannel : WebFishPartner.PartnerReference.WebPartner, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebPartnerClient : System.ServiceModel.ClientBase<WebFishPartner.PartnerReference.WebPartner>, WebFishPartner.PartnerReference.WebPartner {
        
        public WebPartnerClient() {
        }
        
        public WebPartnerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebPartnerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebPartnerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebPartnerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebFishPartner.PartnerReference.ThongTin LayTT(string tokenService, string tokenInfo) {
            return base.Channel.LayTT(tokenService, tokenInfo);
        }
        
        public System.Threading.Tasks.Task<WebFishPartner.PartnerReference.ThongTin> LayTTAsync(string tokenService, string tokenInfo) {
            return base.Channel.LayTTAsync(tokenService, tokenInfo);
        }
    }
}
