//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceWIki.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccService
    {
        public int idAS { get; set; }
        public string nameAS { get; set; }
        public string emailAS { get; set; }
        public string pwdAS { get; set; }
        public string tokenString { get; set; }
        public bool sttAS { get; set; }
    }
}
