//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceWIki.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Information()
        {
            this.EditInfoes = new HashSet<EditInfo>();
            dayCreateInfo = DateTime.Now;
        }
    
        public int idInfor { get; set; }
        public string titleInfo { get; set; }
        public string contentInfo { get; set; }
        public System.DateTime dayCreateInfo { get; set; }
        public int idUser { get; set; }
        public int idCate { get; set; }
        public bool hideInfo { get; set; }
        public bool newInfo { get; set; }
        public string token { get; set; }
        public string nameUnsigned { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EditInfo> EditInfoes { get; set; }
        public virtual User User { get; set; }
    }
}
