//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWiki.MyReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Danhmuc", Namespace="http://schemas.datacontract.org/2004/07/WebServiceWIki.Models.ViewContractModel")]
    [System.SerializableAttribute()]
    public partial class Danhmuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDM {
            get {
                return this.MaDMField;
            }
            set {
                if ((this.MaDMField.Equals(value) != true)) {
                    this.MaDMField = value;
                    this.RaisePropertyChanged("MaDM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDM {
            get {
                return this.TenDMField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDMField, value) != true)) {
                    this.TenDMField = value;
                    this.RaisePropertyChanged("TenDM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThongTin", Namespace="http://schemas.datacontract.org/2004/07/WebServiceWIki.Models.ViewContractModel")]
    [System.SerializableAttribute()]
    public partial class ThongTin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChuDeTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayTaoTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoidungTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TTMoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenTTKhongDauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenTTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AnTT {
            get {
                return this.AnTTField;
            }
            set {
                if ((this.AnTTField.Equals(value) != true)) {
                    this.AnTTField = value;
                    this.RaisePropertyChanged("AnTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChuDeTT {
            get {
                return this.ChuDeTTField;
            }
            set {
                if ((object.ReferenceEquals(this.ChuDeTTField, value) != true)) {
                    this.ChuDeTTField = value;
                    this.RaisePropertyChanged("ChuDeTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDM {
            get {
                return this.MaDMField;
            }
            set {
                if ((this.MaDMField.Equals(value) != true)) {
                    this.MaDMField = value;
                    this.RaisePropertyChanged("MaDM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNguoiDung {
            get {
                return this.MaNguoiDungField;
            }
            set {
                if ((this.MaNguoiDungField.Equals(value) != true)) {
                    this.MaNguoiDungField = value;
                    this.RaisePropertyChanged("MaNguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaTT {
            get {
                return this.MaTTField;
            }
            set {
                if ((this.MaTTField.Equals(value) != true)) {
                    this.MaTTField = value;
                    this.RaisePropertyChanged("MaTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayTaoTT {
            get {
                return this.NgayTaoTTField;
            }
            set {
                if ((this.NgayTaoTTField.Equals(value) != true)) {
                    this.NgayTaoTTField = value;
                    this.RaisePropertyChanged("NgayTaoTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoidungTT {
            get {
                return this.NoidungTTField;
            }
            set {
                if ((object.ReferenceEquals(this.NoidungTTField, value) != true)) {
                    this.NoidungTTField = value;
                    this.RaisePropertyChanged("NoidungTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TTMoi {
            get {
                return this.TTMoiField;
            }
            set {
                if ((this.TTMoiField.Equals(value) != true)) {
                    this.TTMoiField = value;
                    this.RaisePropertyChanged("TTMoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenTTKhongDau {
            get {
                return this.TenTTKhongDauField;
            }
            set {
                if ((object.ReferenceEquals(this.TenTTKhongDauField, value) != true)) {
                    this.TenTTKhongDauField = value;
                    this.RaisePropertyChanged("TenTTKhongDau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenTT {
            get {
                return this.TokenTTField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenTTField, value) != true)) {
                    this.TokenTTField = value;
                    this.RaisePropertyChanged("TokenTT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThongTin_NguoiDung", Namespace="http://schemas.datacontract.org/2004/07/WebServiceWIki.Models.ViewContractModel")]
    [System.SerializableAttribute()]
    public partial class ThongTin_NguoiDung : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChuDeTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool KichHoatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayTaoTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoidungTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TTMoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenTTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AnTT {
            get {
                return this.AnTTField;
            }
            set {
                if ((this.AnTTField.Equals(value) != true)) {
                    this.AnTTField = value;
                    this.RaisePropertyChanged("AnTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChuDeTT {
            get {
                return this.ChuDeTTField;
            }
            set {
                if ((object.ReferenceEquals(this.ChuDeTTField, value) != true)) {
                    this.ChuDeTTField = value;
                    this.RaisePropertyChanged("ChuDeTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool KichHoat {
            get {
                return this.KichHoatField;
            }
            set {
                if ((this.KichHoatField.Equals(value) != true)) {
                    this.KichHoatField = value;
                    this.RaisePropertyChanged("KichHoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDM {
            get {
                return this.MaDMField;
            }
            set {
                if ((this.MaDMField.Equals(value) != true)) {
                    this.MaDMField = value;
                    this.RaisePropertyChanged("MaDM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNguoiDung {
            get {
                return this.MaNguoiDungField;
            }
            set {
                if ((this.MaNguoiDungField.Equals(value) != true)) {
                    this.MaNguoiDungField = value;
                    this.RaisePropertyChanged("MaNguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaTT {
            get {
                return this.MaTTField;
            }
            set {
                if ((this.MaTTField.Equals(value) != true)) {
                    this.MaTTField = value;
                    this.RaisePropertyChanged("MaTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayTaoTT {
            get {
                return this.NgayTaoTTField;
            }
            set {
                if ((this.NgayTaoTTField.Equals(value) != true)) {
                    this.NgayTaoTTField = value;
                    this.RaisePropertyChanged("NgayTaoTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoidungTT {
            get {
                return this.NoidungTTField;
            }
            set {
                if ((object.ReferenceEquals(this.NoidungTTField, value) != true)) {
                    this.NoidungTTField = value;
                    this.RaisePropertyChanged("NoidungTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TTMoi {
            get {
                return this.TTMoiField;
            }
            set {
                if ((this.TTMoiField.Equals(value) != true)) {
                    this.TTMoiField = value;
                    this.RaisePropertyChanged("TTMoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDM {
            get {
                return this.TenDMField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDMField, value) != true)) {
                    this.TenDMField = value;
                    this.RaisePropertyChanged("TenDM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNguoiDung {
            get {
                return this.TenNguoiDungField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNguoiDungField, value) != true)) {
                    this.TenNguoiDungField = value;
                    this.RaisePropertyChanged("TenNguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenTT {
            get {
                return this.TokenTTField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenTTField, value) != true)) {
                    this.TokenTTField = value;
                    this.RaisePropertyChanged("TokenTT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SuaTT", Namespace="http://schemas.datacontract.org/2004/07/WebServiceWIki.Models.ViewContractModel")]
    [System.SerializableAttribute()]
    public partial class SuaTT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSuaTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaySuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoidundSuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuaTTMoiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNguoiDung {
            get {
                return this.MaNguoiDungField;
            }
            set {
                if ((this.MaNguoiDungField.Equals(value) != true)) {
                    this.MaNguoiDungField = value;
                    this.RaisePropertyChanged("MaNguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSuaTT {
            get {
                return this.MaSuaTTField;
            }
            set {
                if ((this.MaSuaTTField.Equals(value) != true)) {
                    this.MaSuaTTField = value;
                    this.RaisePropertyChanged("MaSuaTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaTT {
            get {
                return this.MaTTField;
            }
            set {
                if ((this.MaTTField.Equals(value) != true)) {
                    this.MaTTField = value;
                    this.RaisePropertyChanged("MaTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgaySua {
            get {
                return this.NgaySuaField;
            }
            set {
                if ((this.NgaySuaField.Equals(value) != true)) {
                    this.NgaySuaField = value;
                    this.RaisePropertyChanged("NgaySua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoidundSua {
            get {
                return this.NoidundSuaField;
            }
            set {
                if ((object.ReferenceEquals(this.NoidundSuaField, value) != true)) {
                    this.NoidundSuaField = value;
                    this.RaisePropertyChanged("NoidundSua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuaTTMoi {
            get {
                return this.SuaTTMoiField;
            }
            set {
                if ((this.SuaTTMoiField.Equals(value) != true)) {
                    this.SuaTTMoiField = value;
                    this.RaisePropertyChanged("SuaTTMoi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SuaTT_NguoiDung", Namespace="http://schemas.datacontract.org/2004/07/WebServiceWIki.Models.ViewContractModel")]
    [System.SerializableAttribute()]
    public partial class SuaTT_NguoiDung : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool KichHoatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSuaTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaTTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaySuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoidundSuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuaTTMoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNguoiDungField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool KichHoat {
            get {
                return this.KichHoatField;
            }
            set {
                if ((this.KichHoatField.Equals(value) != true)) {
                    this.KichHoatField = value;
                    this.RaisePropertyChanged("KichHoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNguoiDung {
            get {
                return this.MaNguoiDungField;
            }
            set {
                if ((this.MaNguoiDungField.Equals(value) != true)) {
                    this.MaNguoiDungField = value;
                    this.RaisePropertyChanged("MaNguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSuaTT {
            get {
                return this.MaSuaTTField;
            }
            set {
                if ((this.MaSuaTTField.Equals(value) != true)) {
                    this.MaSuaTTField = value;
                    this.RaisePropertyChanged("MaSuaTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaTT {
            get {
                return this.MaTTField;
            }
            set {
                if ((this.MaTTField.Equals(value) != true)) {
                    this.MaTTField = value;
                    this.RaisePropertyChanged("MaTT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgaySua {
            get {
                return this.NgaySuaField;
            }
            set {
                if ((this.NgaySuaField.Equals(value) != true)) {
                    this.NgaySuaField = value;
                    this.RaisePropertyChanged("NgaySua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoidundSua {
            get {
                return this.NoidundSuaField;
            }
            set {
                if ((object.ReferenceEquals(this.NoidundSuaField, value) != true)) {
                    this.NoidundSuaField = value;
                    this.RaisePropertyChanged("NoidundSua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuaTTMoi {
            get {
                return this.SuaTTMoiField;
            }
            set {
                if ((this.SuaTTMoiField.Equals(value) != true)) {
                    this.SuaTTMoiField = value;
                    this.RaisePropertyChanged("SuaTTMoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNguoiDung {
            get {
                return this.TenNguoiDungField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNguoiDungField, value) != true)) {
                    this.TenNguoiDungField = value;
                    this.RaisePropertyChanged("TenNguoiDung");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NguoiDung", Namespace="http://schemas.datacontract.org/2004/07/WebServiceWIki.Models.ViewContractModel")]
    [System.SerializableAttribute()]
    public partial class NguoiDung : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool KichHoatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaQuyenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatkhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNguoiDungField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool KichHoat {
            get {
                return this.KichHoatField;
            }
            set {
                if ((this.KichHoatField.Equals(value) != true)) {
                    this.KichHoatField = value;
                    this.RaisePropertyChanged("KichHoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNguoiDung {
            get {
                return this.MaNguoiDungField;
            }
            set {
                if ((this.MaNguoiDungField.Equals(value) != true)) {
                    this.MaNguoiDungField = value;
                    this.RaisePropertyChanged("MaNguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaQuyen {
            get {
                return this.MaQuyenField;
            }
            set {
                if ((this.MaQuyenField.Equals(value) != true)) {
                    this.MaQuyenField = value;
                    this.RaisePropertyChanged("MaQuyen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matkhau {
            get {
                return this.MatkhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatkhauField, value) != true)) {
                    this.MatkhauField = value;
                    this.RaisePropertyChanged("Matkhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNguoiDung {
            get {
                return this.TenNguoiDungField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNguoiDungField, value) != true)) {
                    this.TenNguoiDungField = value;
                    this.RaisePropertyChanged("TenNguoiDung");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NguoiDichVu", Namespace="http://schemas.datacontract.org/2004/07/WebServiceWIki.Models.ViewContractModel")]
    [System.SerializableAttribute()]
    public partial class NguoiDichVu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool KichHoatNguoiDVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MKNguoiDVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNguoiDVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailNguoiDVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNguoiDVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenNguoiDVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool KichHoatNguoiDV {
            get {
                return this.KichHoatNguoiDVField;
            }
            set {
                if ((this.KichHoatNguoiDVField.Equals(value) != true)) {
                    this.KichHoatNguoiDVField = value;
                    this.RaisePropertyChanged("KichHoatNguoiDV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MKNguoiDV {
            get {
                return this.MKNguoiDVField;
            }
            set {
                if ((object.ReferenceEquals(this.MKNguoiDVField, value) != true)) {
                    this.MKNguoiDVField = value;
                    this.RaisePropertyChanged("MKNguoiDV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNguoiDV {
            get {
                return this.MaNguoiDVField;
            }
            set {
                if ((this.MaNguoiDVField.Equals(value) != true)) {
                    this.MaNguoiDVField = value;
                    this.RaisePropertyChanged("MaNguoiDV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailNguoiDV {
            get {
                return this.MailNguoiDVField;
            }
            set {
                if ((object.ReferenceEquals(this.MailNguoiDVField, value) != true)) {
                    this.MailNguoiDVField = value;
                    this.RaisePropertyChanged("MailNguoiDV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNguoiDV {
            get {
                return this.TenNguoiDVField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNguoiDVField, value) != true)) {
                    this.TenNguoiDVField = value;
                    this.RaisePropertyChanged("TenNguoiDV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenNguoiDV {
            get {
                return this.TokenNguoiDVField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenNguoiDVField, value) != true)) {
                    this.TokenNguoiDVField = value;
                    this.RaisePropertyChanged("TokenNguoiDV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WikiReference", ConfigurationName="MyReference.MyWikiService")]
    public interface MyWikiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/TaoDM", ReplyAction="WikiReference/MyWikiService/TaoDMResponse")]
        bool TaoDM(WebWiki.MyReference.Danhmuc newCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/TaoDM", ReplyAction="WikiReference/MyWikiService/TaoDMResponse")]
        System.Threading.Tasks.Task<bool> TaoDMAsync(WebWiki.MyReference.Danhmuc newCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/DSDM", ReplyAction="WikiReference/MyWikiService/DSDMResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.Danhmuc> DSDM();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/DSDM", ReplyAction="WikiReference/MyWikiService/DSDMResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.Danhmuc>> DSDMAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayDM", ReplyAction="WikiReference/MyWikiService/LayDMResponse")]
        WebWiki.MyReference.Danhmuc LayDM(int idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayDM", ReplyAction="WikiReference/MyWikiService/LayDMResponse")]
        System.Threading.Tasks.Task<WebWiki.MyReference.Danhmuc> LayDMAsync(int idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/SuaDM", ReplyAction="WikiReference/MyWikiService/SuaDMResponse")]
        bool SuaDM(WebWiki.MyReference.Danhmuc cate);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/SuaDM", ReplyAction="WikiReference/MyWikiService/SuaDMResponse")]
        System.Threading.Tasks.Task<bool> SuaDMAsync(WebWiki.MyReference.Danhmuc cate);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/XoaDM", ReplyAction="WikiReference/MyWikiService/XoaDMResponse")]
        bool XoaDM(int idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/XoaDM", ReplyAction="WikiReference/MyWikiService/XoaDMResponse")]
        System.Threading.Tasks.Task<bool> XoaDMAsync(int idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayCBBCate", ReplyAction="WikiReference/MyWikiService/LayCBBCateResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.Danhmuc> LayCBBCate(int idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayCBBCate", ReplyAction="WikiReference/MyWikiService/LayCBBCateResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.Danhmuc>> LayCBBCateAsync(int idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/TaoTT", ReplyAction="WikiReference/MyWikiService/TaoTTResponse")]
        bool TaoTT(WebWiki.MyReference.ThongTin newInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/TaoTT", ReplyAction="WikiReference/MyWikiService/TaoTTResponse")]
        System.Threading.Tasks.Task<bool> TaoTTAsync(WebWiki.MyReference.ThongTin newInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/DSTTAdmin", ReplyAction="WikiReference/MyWikiService/DSTTAdminResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> DSTTAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/DSTTAdmin", ReplyAction="WikiReference/MyWikiService/DSTTAdminResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> DSTTAdminAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTNguoiDung", ReplyAction="WikiReference/MyWikiService/LayTTNguoiDungResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayTTNguoiDung();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTNguoiDung", ReplyAction="WikiReference/MyWikiService/LayTTNguoiDungResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayTTNguoiDungAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTTheoNguoiDung", ReplyAction="WikiReference/MyWikiService/LayTTTheoNguoiDungResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.ThongTin> LayTTTheoNguoiDung(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTTheoNguoiDung", ReplyAction="WikiReference/MyWikiService/LayTTTheoNguoiDungResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin>> LayTTTheoNguoiDungAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTMoiNguoiDung", ReplyAction="WikiReference/MyWikiService/LayTTMoiNguoiDungResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayTTMoiNguoiDung();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTMoiNguoiDung", ReplyAction="WikiReference/MyWikiService/LayTTMoiNguoiDungResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayTTMoiNguoiDungAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTAnNguoiDung", ReplyAction="WikiReference/MyWikiService/LayTTAnNguoiDungResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayTTAnNguoiDung();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTAnNguoiDung", ReplyAction="WikiReference/MyWikiService/LayTTAnNguoiDungResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayTTAnNguoiDungAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTAnAdmin", ReplyAction="WikiReference/MyWikiService/LayTTAnAdminResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayTTAnAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTAnAdmin", ReplyAction="WikiReference/MyWikiService/LayTTAnAdminResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayTTAnAdminAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTAnTheoNguoidung", ReplyAction="WikiReference/MyWikiService/LayTTAnTheoNguoidungResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayTTAnTheoNguoidung(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTAnTheoNguoidung", ReplyAction="WikiReference/MyWikiService/LayTTAnTheoNguoidungResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayTTAnTheoNguoidungAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTTheoDM", ReplyAction="WikiReference/MyWikiService/LayTTTheoDMResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayTTTheoDM(int idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTTheoDM", ReplyAction="WikiReference/MyWikiService/LayTTTheoDMResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayTTTheoDMAsync(int idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayHetTTTheoNguoiDung", ReplyAction="WikiReference/MyWikiService/LayHetTTTheoNguoiDungResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayHetTTTheoNguoiDung(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayHetTTTheoNguoiDung", ReplyAction="WikiReference/MyWikiService/LayHetTTTheoNguoiDungResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayHetTTTheoNguoiDungAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTNgauNhien", ReplyAction="WikiReference/MyWikiService/LayTTNgauNhienResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayTTNgauNhien();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTTNgauNhien", ReplyAction="WikiReference/MyWikiService/LayTTNgauNhienResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayTTNgauNhienAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/Lay3TT", ReplyAction="WikiReference/MyWikiService/Lay3TTResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> Lay3TT(int idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/Lay3TT", ReplyAction="WikiReference/MyWikiService/Lay3TTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> Lay3TTAsync(int idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTT", ReplyAction="WikiReference/MyWikiService/LayTTResponse")]
        WebWiki.MyReference.ThongTin_NguoiDung LayTT(int idIF);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTT", ReplyAction="WikiReference/MyWikiService/LayTTResponse")]
        System.Threading.Tasks.Task<WebWiki.MyReference.ThongTin_NguoiDung> LayTTAsync(int idIF);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/SuaTT", ReplyAction="WikiReference/MyWikiService/SuaTTResponse")]
        bool SuaTT(WebWiki.MyReference.ThongTin i);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/SuaTT", ReplyAction="WikiReference/MyWikiService/SuaTTResponse")]
        System.Threading.Tasks.Task<bool> SuaTTAsync(WebWiki.MyReference.ThongTin i);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/XoaTT", ReplyAction="WikiReference/MyWikiService/XoaTTResponse")]
        bool XoaTT(int idIF);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/XoaTT", ReplyAction="WikiReference/MyWikiService/XoaTTResponse")]
        System.Threading.Tasks.Task<bool> XoaTTAsync(int idIF);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/DocTTMoi", ReplyAction="WikiReference/MyWikiService/DocTTMoiResponse")]
        bool DocTTMoi(int idIF);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/DocTTMoi", ReplyAction="WikiReference/MyWikiService/DocTTMoiResponse")]
        System.Threading.Tasks.Task<bool> DocTTMoiAsync(int idIF);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/AnMotTT", ReplyAction="WikiReference/MyWikiService/AnMotTTResponse")]
        bool AnMotTT(int idIF);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/AnMotTT", ReplyAction="WikiReference/MyWikiService/AnMotTTResponse")]
        System.Threading.Tasks.Task<bool> AnMotTTAsync(int idIF);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/TimKiemTT", ReplyAction="WikiReference/MyWikiService/TimKiemTTResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.ThongTin> TimKiemTT(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/TimKiemTT", ReplyAction="WikiReference/MyWikiService/TimKiemTTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin>> TimKiemTTAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/TTTimKiem", ReplyAction="WikiReference/MyWikiService/TTTimKiemResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> TTTimKiem(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/TTTimKiem", ReplyAction="WikiReference/MyWikiService/TTTimKiemResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> TTTimKiemAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/TaoSuaTT", ReplyAction="WikiReference/MyWikiService/TaoSuaTTResponse")]
        bool TaoSuaTT(WebWiki.MyReference.SuaTT newEdit);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/TaoSuaTT", ReplyAction="WikiReference/MyWikiService/TaoSuaTTResponse")]
        System.Threading.Tasks.Task<bool> TaoSuaTTAsync(WebWiki.MyReference.SuaTT newEdit);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/DSSTT", ReplyAction="WikiReference/MyWikiService/DSSTTResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung> DSSTT(int idIF);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/DSSTT", ReplyAction="WikiReference/MyWikiService/DSSTTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung>> DSSTTAsync(int idIF);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/DocSuaTTMoi", ReplyAction="WikiReference/MyWikiService/DocSuaTTMoiResponse")]
        bool DocSuaTTMoi(int idEI);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/DocSuaTTMoi", ReplyAction="WikiReference/MyWikiService/DocSuaTTMoiResponse")]
        System.Threading.Tasks.Task<bool> DocSuaTTMoiAsync(int idEI);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/XoaSuaTT", ReplyAction="WikiReference/MyWikiService/XoaSuaTTResponse")]
        bool XoaSuaTT(int idEI);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/XoaSuaTT", ReplyAction="WikiReference/MyWikiService/XoaSuaTTResponse")]
        System.Threading.Tasks.Task<bool> XoaSuaTTAsync(int idEI);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayBLNguoiDung", ReplyAction="WikiReference/MyWikiService/LayBLNguoiDungResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung> LayBLNguoiDung(int idIF);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayBLNguoiDung", ReplyAction="WikiReference/MyWikiService/LayBLNguoiDungResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung>> LayBLNguoiDungAsync(int idIF);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/XoaSuaTTTheoMaSua", ReplyAction="WikiReference/MyWikiService/XoaSuaTTTheoMaSuaResponse")]
        bool XoaSuaTTTheoMaSua(int idEI);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/XoaSuaTTTheoMaSua", ReplyAction="WikiReference/MyWikiService/XoaSuaTTTheoMaSuaResponse")]
        System.Threading.Tasks.Task<bool> XoaSuaTTTheoMaSuaAsync(int idEI);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayBLMoiTheoNguoiDung", ReplyAction="WikiReference/MyWikiService/LayBLMoiTheoNguoiDungResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung> LayBLMoiTheoNguoiDung(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayBLMoiTheoNguoiDung", ReplyAction="WikiReference/MyWikiService/LayBLMoiTheoNguoiDungResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung>> LayBLMoiTheoNguoiDungAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayBLDaXemTheoNguoiDung", ReplyAction="WikiReference/MyWikiService/LayBLDaXemTheoNguoiDungResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung> LayBLDaXemTheoNguoiDung(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayBLDaXemTheoNguoiDung", ReplyAction="WikiReference/MyWikiService/LayBLDaXemTheoNguoiDungResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung>> LayBLDaXemTheoNguoiDungAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTatCaNguoiDung", ReplyAction="WikiReference/MyWikiService/LayTatCaNguoiDungResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.NguoiDung> LayTatCaNguoiDung();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/LayTatCaNguoiDung", ReplyAction="WikiReference/MyWikiService/LayTatCaNguoiDungResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.NguoiDung>> LayTatCaNguoiDungAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/KichHoatNguoiDung", ReplyAction="WikiReference/MyWikiService/KichHoatNguoiDungResponse")]
        bool KichHoatNguoiDung(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/KichHoatNguoiDung", ReplyAction="WikiReference/MyWikiService/KichHoatNguoiDungResponse")]
        System.Threading.Tasks.Task<bool> KichHoatNguoiDungAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/KiemTraNguoiDung", ReplyAction="WikiReference/MyWikiService/KiemTraNguoiDungResponse")]
        int KiemTraNguoiDung(string mail, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/KiemTraNguoiDung", ReplyAction="WikiReference/MyWikiService/KiemTraNguoiDungResponse")]
        System.Threading.Tasks.Task<int> KiemTraNguoiDungAsync(string mail, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/TaoNguoiDung", ReplyAction="WikiReference/MyWikiService/TaoNguoiDungResponse")]
        int TaoNguoiDung(WebWiki.MyReference.NguoiDung u);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/TaoNguoiDung", ReplyAction="WikiReference/MyWikiService/TaoNguoiDungResponse")]
        System.Threading.Tasks.Task<int> TaoNguoiDungAsync(WebWiki.MyReference.NguoiDung u);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/NguoiDungDangNhap", ReplyAction="WikiReference/MyWikiService/NguoiDungDangNhapResponse")]
        WebWiki.MyReference.NguoiDung NguoiDungDangNhap(string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/NguoiDungDangNhap", ReplyAction="WikiReference/MyWikiService/NguoiDungDangNhapResponse")]
        System.Threading.Tasks.Task<WebWiki.MyReference.NguoiDung> NguoiDungDangNhapAsync(string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/CapNhatThongTin", ReplyAction="WikiReference/MyWikiService/CapNhatThongTinResponse")]
        int CapNhatThongTin(WebWiki.MyReference.NguoiDung u);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/CapNhatThongTin", ReplyAction="WikiReference/MyWikiService/CapNhatThongTinResponse")]
        System.Threading.Tasks.Task<int> CapNhatThongTinAsync(WebWiki.MyReference.NguoiDung u);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/DoiMatKhauNguoiDung", ReplyAction="WikiReference/MyWikiService/DoiMatKhauNguoiDungResponse")]
        bool DoiMatKhauNguoiDung(int idUser, string pwdOld, string pwdNew);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/DoiMatKhauNguoiDung", ReplyAction="WikiReference/MyWikiService/DoiMatKhauNguoiDungResponse")]
        System.Threading.Tasks.Task<bool> DoiMatKhauNguoiDungAsync(int idUser, string pwdOld, string pwdNew);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/TaoNguoiDV", ReplyAction="WikiReference/MyWikiService/TaoNguoiDVResponse")]
        bool TaoNguoiDV(WebWiki.MyReference.NguoiDichVu a);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/TaoNguoiDV", ReplyAction="WikiReference/MyWikiService/TaoNguoiDVResponse")]
        System.Threading.Tasks.Task<bool> TaoNguoiDVAsync(WebWiki.MyReference.NguoiDichVu a);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/NguoiDVDangNhap", ReplyAction="WikiReference/MyWikiService/NguoiDVDangNhapResponse")]
        WebWiki.MyReference.NguoiDichVu NguoiDVDangNhap(string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/NguoiDVDangNhap", ReplyAction="WikiReference/MyWikiService/NguoiDVDangNhapResponse")]
        System.Threading.Tasks.Task<WebWiki.MyReference.NguoiDichVu> NguoiDVDangNhapAsync(string mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/DSAS", ReplyAction="WikiReference/MyWikiService/DSASResponse")]
        System.Collections.Generic.List<WebWiki.MyReference.NguoiDichVu> DSAS();
        
        [System.ServiceModel.OperationContractAttribute(Action="WikiReference/MyWikiService/DSAS", ReplyAction="WikiReference/MyWikiService/DSASResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.NguoiDichVu>> DSASAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWikiServiceChannel : WebWiki.MyReference.MyWikiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWikiServiceClient : System.ServiceModel.ClientBase<WebWiki.MyReference.MyWikiService>, WebWiki.MyReference.MyWikiService {
        
        public MyWikiServiceClient() {
        }
        
        public MyWikiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWikiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWikiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWikiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TaoDM(WebWiki.MyReference.Danhmuc newCate) {
            return base.Channel.TaoDM(newCate);
        }
        
        public System.Threading.Tasks.Task<bool> TaoDMAsync(WebWiki.MyReference.Danhmuc newCate) {
            return base.Channel.TaoDMAsync(newCate);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.Danhmuc> DSDM() {
            return base.Channel.DSDM();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.Danhmuc>> DSDMAsync() {
            return base.Channel.DSDMAsync();
        }
        
        public WebWiki.MyReference.Danhmuc LayDM(int idCate) {
            return base.Channel.LayDM(idCate);
        }
        
        public System.Threading.Tasks.Task<WebWiki.MyReference.Danhmuc> LayDMAsync(int idCate) {
            return base.Channel.LayDMAsync(idCate);
        }
        
        public bool SuaDM(WebWiki.MyReference.Danhmuc cate) {
            return base.Channel.SuaDM(cate);
        }
        
        public System.Threading.Tasks.Task<bool> SuaDMAsync(WebWiki.MyReference.Danhmuc cate) {
            return base.Channel.SuaDMAsync(cate);
        }
        
        public bool XoaDM(int idCate) {
            return base.Channel.XoaDM(idCate);
        }
        
        public System.Threading.Tasks.Task<bool> XoaDMAsync(int idCate) {
            return base.Channel.XoaDMAsync(idCate);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.Danhmuc> LayCBBCate(int idCate) {
            return base.Channel.LayCBBCate(idCate);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.Danhmuc>> LayCBBCateAsync(int idCate) {
            return base.Channel.LayCBBCateAsync(idCate);
        }
        
        public bool TaoTT(WebWiki.MyReference.ThongTin newInfo) {
            return base.Channel.TaoTT(newInfo);
        }
        
        public System.Threading.Tasks.Task<bool> TaoTTAsync(WebWiki.MyReference.ThongTin newInfo) {
            return base.Channel.TaoTTAsync(newInfo);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> DSTTAdmin() {
            return base.Channel.DSTTAdmin();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> DSTTAdminAsync() {
            return base.Channel.DSTTAdminAsync();
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayTTNguoiDung() {
            return base.Channel.LayTTNguoiDung();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayTTNguoiDungAsync() {
            return base.Channel.LayTTNguoiDungAsync();
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.ThongTin> LayTTTheoNguoiDung(int idUser) {
            return base.Channel.LayTTTheoNguoiDung(idUser);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin>> LayTTTheoNguoiDungAsync(int idUser) {
            return base.Channel.LayTTTheoNguoiDungAsync(idUser);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayTTMoiNguoiDung() {
            return base.Channel.LayTTMoiNguoiDung();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayTTMoiNguoiDungAsync() {
            return base.Channel.LayTTMoiNguoiDungAsync();
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayTTAnNguoiDung() {
            return base.Channel.LayTTAnNguoiDung();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayTTAnNguoiDungAsync() {
            return base.Channel.LayTTAnNguoiDungAsync();
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayTTAnAdmin() {
            return base.Channel.LayTTAnAdmin();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayTTAnAdminAsync() {
            return base.Channel.LayTTAnAdminAsync();
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayTTAnTheoNguoidung(int idUser) {
            return base.Channel.LayTTAnTheoNguoidung(idUser);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayTTAnTheoNguoidungAsync(int idUser) {
            return base.Channel.LayTTAnTheoNguoidungAsync(idUser);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayTTTheoDM(int idCate) {
            return base.Channel.LayTTTheoDM(idCate);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayTTTheoDMAsync(int idCate) {
            return base.Channel.LayTTTheoDMAsync(idCate);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayHetTTTheoNguoiDung(int idUser) {
            return base.Channel.LayHetTTTheoNguoiDung(idUser);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayHetTTTheoNguoiDungAsync(int idUser) {
            return base.Channel.LayHetTTTheoNguoiDungAsync(idUser);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> LayTTNgauNhien() {
            return base.Channel.LayTTNgauNhien();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> LayTTNgauNhienAsync() {
            return base.Channel.LayTTNgauNhienAsync();
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> Lay3TT(int idCate) {
            return base.Channel.Lay3TT(idCate);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> Lay3TTAsync(int idCate) {
            return base.Channel.Lay3TTAsync(idCate);
        }
        
        public WebWiki.MyReference.ThongTin_NguoiDung LayTT(int idIF) {
            return base.Channel.LayTT(idIF);
        }
        
        public System.Threading.Tasks.Task<WebWiki.MyReference.ThongTin_NguoiDung> LayTTAsync(int idIF) {
            return base.Channel.LayTTAsync(idIF);
        }
        
        public bool SuaTT(WebWiki.MyReference.ThongTin i) {
            return base.Channel.SuaTT(i);
        }
        
        public System.Threading.Tasks.Task<bool> SuaTTAsync(WebWiki.MyReference.ThongTin i) {
            return base.Channel.SuaTTAsync(i);
        }
        
        public bool XoaTT(int idIF) {
            return base.Channel.XoaTT(idIF);
        }
        
        public System.Threading.Tasks.Task<bool> XoaTTAsync(int idIF) {
            return base.Channel.XoaTTAsync(idIF);
        }
        
        public bool DocTTMoi(int idIF) {
            return base.Channel.DocTTMoi(idIF);
        }
        
        public System.Threading.Tasks.Task<bool> DocTTMoiAsync(int idIF) {
            return base.Channel.DocTTMoiAsync(idIF);
        }
        
        public bool AnMotTT(int idIF) {
            return base.Channel.AnMotTT(idIF);
        }
        
        public System.Threading.Tasks.Task<bool> AnMotTTAsync(int idIF) {
            return base.Channel.AnMotTTAsync(idIF);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.ThongTin> TimKiemTT(string value) {
            return base.Channel.TimKiemTT(value);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin>> TimKiemTTAsync(string value) {
            return base.Channel.TimKiemTTAsync(value);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung> TTTimKiem(string value) {
            return base.Channel.TTTimKiem(value);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.ThongTin_NguoiDung>> TTTimKiemAsync(string value) {
            return base.Channel.TTTimKiemAsync(value);
        }
        
        public bool TaoSuaTT(WebWiki.MyReference.SuaTT newEdit) {
            return base.Channel.TaoSuaTT(newEdit);
        }
        
        public System.Threading.Tasks.Task<bool> TaoSuaTTAsync(WebWiki.MyReference.SuaTT newEdit) {
            return base.Channel.TaoSuaTTAsync(newEdit);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung> DSSTT(int idIF) {
            return base.Channel.DSSTT(idIF);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung>> DSSTTAsync(int idIF) {
            return base.Channel.DSSTTAsync(idIF);
        }
        
        public bool DocSuaTTMoi(int idEI) {
            return base.Channel.DocSuaTTMoi(idEI);
        }
        
        public System.Threading.Tasks.Task<bool> DocSuaTTMoiAsync(int idEI) {
            return base.Channel.DocSuaTTMoiAsync(idEI);
        }
        
        public bool XoaSuaTT(int idEI) {
            return base.Channel.XoaSuaTT(idEI);
        }
        
        public System.Threading.Tasks.Task<bool> XoaSuaTTAsync(int idEI) {
            return base.Channel.XoaSuaTTAsync(idEI);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung> LayBLNguoiDung(int idIF) {
            return base.Channel.LayBLNguoiDung(idIF);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung>> LayBLNguoiDungAsync(int idIF) {
            return base.Channel.LayBLNguoiDungAsync(idIF);
        }
        
        public bool XoaSuaTTTheoMaSua(int idEI) {
            return base.Channel.XoaSuaTTTheoMaSua(idEI);
        }
        
        public System.Threading.Tasks.Task<bool> XoaSuaTTTheoMaSuaAsync(int idEI) {
            return base.Channel.XoaSuaTTTheoMaSuaAsync(idEI);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung> LayBLMoiTheoNguoiDung(int idUser) {
            return base.Channel.LayBLMoiTheoNguoiDung(idUser);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung>> LayBLMoiTheoNguoiDungAsync(int idUser) {
            return base.Channel.LayBLMoiTheoNguoiDungAsync(idUser);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung> LayBLDaXemTheoNguoiDung(int idUser) {
            return base.Channel.LayBLDaXemTheoNguoiDung(idUser);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.SuaTT_NguoiDung>> LayBLDaXemTheoNguoiDungAsync(int idUser) {
            return base.Channel.LayBLDaXemTheoNguoiDungAsync(idUser);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.NguoiDung> LayTatCaNguoiDung() {
            return base.Channel.LayTatCaNguoiDung();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.NguoiDung>> LayTatCaNguoiDungAsync() {
            return base.Channel.LayTatCaNguoiDungAsync();
        }
        
        public bool KichHoatNguoiDung(int idUser) {
            return base.Channel.KichHoatNguoiDung(idUser);
        }
        
        public System.Threading.Tasks.Task<bool> KichHoatNguoiDungAsync(int idUser) {
            return base.Channel.KichHoatNguoiDungAsync(idUser);
        }
        
        public int KiemTraNguoiDung(string mail, string pwd) {
            return base.Channel.KiemTraNguoiDung(mail, pwd);
        }
        
        public System.Threading.Tasks.Task<int> KiemTraNguoiDungAsync(string mail, string pwd) {
            return base.Channel.KiemTraNguoiDungAsync(mail, pwd);
        }
        
        public int TaoNguoiDung(WebWiki.MyReference.NguoiDung u) {
            return base.Channel.TaoNguoiDung(u);
        }
        
        public System.Threading.Tasks.Task<int> TaoNguoiDungAsync(WebWiki.MyReference.NguoiDung u) {
            return base.Channel.TaoNguoiDungAsync(u);
        }
        
        public WebWiki.MyReference.NguoiDung NguoiDungDangNhap(string mail) {
            return base.Channel.NguoiDungDangNhap(mail);
        }
        
        public System.Threading.Tasks.Task<WebWiki.MyReference.NguoiDung> NguoiDungDangNhapAsync(string mail) {
            return base.Channel.NguoiDungDangNhapAsync(mail);
        }
        
        public int CapNhatThongTin(WebWiki.MyReference.NguoiDung u) {
            return base.Channel.CapNhatThongTin(u);
        }
        
        public System.Threading.Tasks.Task<int> CapNhatThongTinAsync(WebWiki.MyReference.NguoiDung u) {
            return base.Channel.CapNhatThongTinAsync(u);
        }
        
        public bool DoiMatKhauNguoiDung(int idUser, string pwdOld, string pwdNew) {
            return base.Channel.DoiMatKhauNguoiDung(idUser, pwdOld, pwdNew);
        }
        
        public System.Threading.Tasks.Task<bool> DoiMatKhauNguoiDungAsync(int idUser, string pwdOld, string pwdNew) {
            return base.Channel.DoiMatKhauNguoiDungAsync(idUser, pwdOld, pwdNew);
        }
        
        public bool TaoNguoiDV(WebWiki.MyReference.NguoiDichVu a) {
            return base.Channel.TaoNguoiDV(a);
        }
        
        public System.Threading.Tasks.Task<bool> TaoNguoiDVAsync(WebWiki.MyReference.NguoiDichVu a) {
            return base.Channel.TaoNguoiDVAsync(a);
        }
        
        public WebWiki.MyReference.NguoiDichVu NguoiDVDangNhap(string mail) {
            return base.Channel.NguoiDVDangNhap(mail);
        }
        
        public System.Threading.Tasks.Task<WebWiki.MyReference.NguoiDichVu> NguoiDVDangNhapAsync(string mail) {
            return base.Channel.NguoiDVDangNhapAsync(mail);
        }
        
        public System.Collections.Generic.List<WebWiki.MyReference.NguoiDichVu> DSAS() {
            return base.Channel.DSAS();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WebWiki.MyReference.NguoiDichVu>> DSASAsync() {
            return base.Channel.DSASAsync();
        }
    }
}
